[build]
# Target musl-libc by default when running Cargo.
#target = "x86_64-unknown-linux-musl"
#target = "aarch64-unknown-linux-musl"
#target = "armv7-unknown-linux-musleabihf"

[target.armv7-unknown-linux-musleabihf]
rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]
linker = "musl-gcc"

[target.aarch64-unknown-linux-musl]
rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]
linker = "musl-gcc"
